# Add application configuration variables here, as shown below.
#
# Twitter config
consumer_key: xxx
consumer_secret: xxx
oauth_token: xxx
oauth_token_secret: xxx
# image upload
s3_access_key_id: xxx
s3_secret_access_key: xxx
s3_bucket: xxx
# new relic
NEW_RELIC_LICENSE_KEY: xxx
NEW_RELIC_APP_NAME: xxx
# analytics
GOOGLE_ANALYTICS_ACCOUNT: UA-xxx
# optional
# GOOGLE_ANALYTICS_DOMAIN: xxx
# optional
# BUNDLE_GEMFILE:
# CUCUMBER_FORMAT:
# NO_RUBYGEMS: false
# GUARD_NOTIFY: false
